### ISSUE TITLE
when using config_file then markdowncli reports it cannot parse or find the config file

### ISSUE THREAD

**Issue by nvtkaszpir** [nosborn/github-action-markdown-cli#1]
example config:

```yaml
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1
        with:
          files:  .
          config_file: .markdownlint.yaml
```
Which returns message (but run does not end in error):
```Cannot read or parse config file '.markdownlint.yaml'```

But wait, there is more!
What works is when we override files, to actually sneak in the parameters into the command executed in entrypoint:

```
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1
        with:
          files: -c .markdownlint.yaml .
```
and then the error message disappears (which means the file is executed and parsed), but is  a hack.

Probabaly the same thing happens with `ignore_files` and `rules` (I have not tested it).

Example code with output https://github.com/nvtkaszpir/rpi/pull/1/checks
