### ISSUE TITLE
Add the ability to configure a patterns file (the `-p` flag)

### ISSUE THREAD

**Issue by jzelinskie** [nosborn/github-action-markdown-cli#16]
I'd like to be able to reuse my `.gitignore` file as the canonical source of files that markdownlint should ignore.

I'd like to be able to do

```yaml
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v2.0.0
        with:
          files: .
          config_file: ".markdownlint.yaml"
          ignore_patterns_file: ".gitginore"
```
